### ISSUE TITLE
Residuals and RegressionParameters::pairs API confusing

### ISSUE THREAD

**Issue by dbr** [n1m3/linregress#8]
Not a huge problem, just a bit surprising that the `RegressionModel.residuals` is returned in the same struct as the others data, but is a different "shape" of data, so when accessed via `.pairs()` truncates most of the data

For example, the debug output shows this:

```
    ...
    pvalues: RegressionParameters {
        intercept_value: 5.749549530737332e-269,
        regressor_names: [
            "x1",
            "x2",
        ],
        regressor_values: [
            9.27933982277656e-11,
            0.0008234351722466723,
        ],
    },
    residuals: RegressionParameters {
        intercept_value: -27.015828794746632,
        regressor_names: [
            "x1",
            "x2",
        ],
        regressor_values: [
            -29.59495810026061,
            -26.127909406281596,
            -26.19444350122059,
            -26.362871508164616,
            -26.362871508164616,
            -29.145193769650938,
            -25.75539341699686,
            ...
```

Accessing `pvalues` using `.pairs()` would return the expected data (e.g `[("x1", 9.27933982277656e-11"), ("x2", 0.0008234351722466723)]`)

Problem is doing same for `residuals` would only return `[("x1", -29.59495810026061), ("x2", -26.127909406281596)]`

**Comment by n1m3** [comment]
Hi, thanks for pointing this out! The residuals really should not be stored in a `RegressionParameters` and overall
I think it would be better to just get rid of the `RegressionParameters` struct in general.

The fields on the model structs should probably be made private in favor of appropriate accessor methods.

The crate could really use a general redesign though. Lot's of design decisions that are a little bizarre in retrospect.

**Comment by n1m3** [comment]
Since `LowLevelRegressionModel` already was pretty much what I wanted, I've gone ahead and implemented my idea.
There's an [alpha version](https://crates.io/crates/linregress/0.5.0-alpha.1) available for testing.

Also see [CHANGELOG.md](https://github.com/n1m3/linregress/blob/master/CHANGELOG.md).
